myweb/myweb/urls.py
from django.contrib import admin
from django.urls import path,include,re_path  # 注意这里多了一个 include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('searchblog.urls')),  # 包含 searchblog 应用的所有 URL
]

myweb/searchblog/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='A valid email address is required.')
    gender = forms.ChoiceField(choices=CustomUser.GENDER_CHOICES)
    favorite_field = forms.CharField(required=False, help_text='Optional.')
    occupation = forms.CharField(required=False, help_text='Optional.')

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('email', 'gender', 'favorite_field', 'occupation')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.gender = self.cleaned_data["gender"]
        user.favorite_field = self.cleaned_data["favorite_field"]
        user.occupation = self.cleaned_data["occupation"]
        if commit:
            user.save()
        return user

myweb/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>{% block title %}博客搜索引擎Blog{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

myweb/templates/login.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>基于用户兴趣的搜索引擎 - 登录</title>

  <!-- Custom fonts for this template-->
  <link href="/static/admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="/static/admin/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">
  <!-- 这里是登录表单的其余部分 -->
  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">登录！体验姐的辛苦劳动成果～</h1>
                  </div>
                  <form action="{% url 'login' %}" method="post" class="user">
                    {% csrf_token %}
                    <div class="form-group">
                      <input name="username" type="text" class="form-control form-control-user" id="id_username"
                        placeholder="用户名" required>
                    </div>
                    <div class="form-group">
                      <input name="password" type="password" class="form-control form-control-user" id="id_password"
                        placeholder="密码" required>
                    </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block">
                      立即登录
                    </button>
                    <hr>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'register' %}">创建一个账户？</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="/static/admin/vendor/jquery/jquery.min.js"></script>
  <script src="/static/admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/static/admin/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="/static/admin/js/sb-admin-2.min.js"></script>

</body>

</html>

myweb/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>基于用户兴趣的搜索引擎 - 注册</title>

  <!-- Custom fonts for this template-->
  <link href="/static/admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="/static/admin/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">
  <!-- 这里是登录表单的其余部分 -->
  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">优雅地创建一个账户</h1>
              </div>
              <form method="post" action="{% url 'register' %}" class="user">
                {% csrf_token %}
                {% csrf_token %}
                <div class="form-group">
                  <input type="text" name="username" id="id_username" class="form-control form-control-user"
                    placeholder="用户名" required>
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="password" name="password1" id="id_password1" class="form-control form-control-user"
                      placeholder="密码" required>
                  </div>
                  <div class="col-sm-6">
                    <input type="password" name="password2" id="id_password2" class="form-control form-control-user"
                      placeholder="重复密码" required>
                  </div>
                </div>
                <div class="form-group">
                  <input type="email" name="email" id="id_email" class="form-control form-control-user" placeholder="邮箱"
                    required>
                </div>
                <div class="form-group">
                  <select name="gender" id="id_gender" class="form-control">
                    <option value="M">Male</option>
                    <option value="F">Female</option>
                    <option value="O">Other</option>
                  </select>
                </div>
                <div class="form-group">
                  <input type="text" name="favorite_field" id="id_favorite_field" class="form-control form-control-user"
                    placeholder="喜好领域">
                </div>
                <div class="form-group">
                  <input type="text" name="occupation" id="id_occupation" class="form-control form-control-user"
                    placeholder="职业">
                </div>
                <button type="submit" class="btn btn-primary btn-user btn-block">
                  立即注册
                </button>
                <hr>
              </form>
              <hr>
              <div class="text-center">
                {% for key, error in register_form.errors.items %}{{ error }}{% endfor %}
                <a class="small" href="{% url 'login' %}">已经有账户了? 立即登录</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="/static/admin/vendor/jquery/jquery.min.js"></script>
  <script src="/static/admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/static/admin/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="/static/admin/js/sb-admin-2.min.js"></script>

</body>

</html>

myweb/templates/results.html
<!-- searchapp/templates/search.html -->
{% load static %}
{% load my_filters %}
<html>
<head>
    <title>博客搜索引擎Blog</title>
    <script src="{% static 'js/jquery.min.js' %}"></script> <!-- 确保已经加载了jQuery -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/result.css' %}">
    <script>
        function takeSnapshot(url) {
            $.ajax({
                url: '{% url "snapshot" %}', // Django的URL名称为snapshot的视图
                type: 'POST',
                data: { 'url': url },
                success: function(data) {
                    alert('网页快照保存成功!');
                },
                error: function(error) {
                    alert('Error taking snapshot: ' + error);
                }
            });
        }
        function recordClick(url) {
            $.ajax({
                url: '{% url "record_click" %}',
                type: 'POST',
                data: {
                    'url': url,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response) {
                    console.log("Click recorded");
                }
            });
        }
    </script>
</head>

<body>
    <div class="header">
        <!-- 搜索表单，让用户可以重新搜索 -->
        <div class="search-form">
            <form method="get" action="{% url 'search_results' %}">
                <input type="text" name="q" placeholder="Search..." value="{{ query }}">
                <select name="type">
                    <option value="standard" {% if query_type == "standard" %}selected{% endif %}>站内查询</option>
                    <option value="phrase" {% if query_type == "phrase" %}selected{% endif %}>短语查询</option>
                    <option value="wildcard" {% if query_type == "wildcard" %}selected{% endif %}>通配查询</option>
                </select>
                <!-- 新增排序方式选择 -->
                <select name="sort_method">
                    <option value="personalize_search" {% if sort_method == "personalize_search" %}selected{% endif %}>个性化查询</option>
                    <option value="pagerank_only" {% if sort_method == "pagerank_only" %}selected{% endif %}>仅PageRank</option>
                </select>
                <button type="submit">查询</button>
            </form>
        </div>
        <!-- 添加查看查询日志的链接 -->
        <a href="{% url 'view_search_logs' %}" class="search-log-link">查看查询日志</a>
    </div>

    <div class="main-content">
        <!-- 修改搜索结果部分 -->
        <div class="search-results">
            <ul>
                {% for result in page_obj %}
                    <li class="search-Item">
                        <h2>{{ result.title }}</h2>
                        <p>{{ result.abstract }}</p>
                        <a href="{{ result.url }}" onclick="recordClick('{{ result.url }}')">阅读原文</a>
                        <!-- 添加一个链接，让用户可以保存网页快照 -->
                        <a href="#" onclick="takeSnapshot('{{ result.url }}'); return false;">保存网页快照</a>
                    </li>
                {% empty %}
                    <li>查询结果为空</li>
                {% endfor %}
            </ul>
        </div>
        <!-- 推荐文章区域 -->
        <div class="recommendations">
            <h2>也许你感兴趣～</h2>
            <ul>
                {% for url in recommendations %}
                    <li class="recommend-Item">
                        <!-- 使用 url_to_title 字典来显示标题，如果字典中没有标题，则显示 URL -->
                        <a href="{{ url }}" onclick="recordClick('{{ url }}');" target="_blank">
                            {{ url_to_title|get_item:url|default:url }}
                        </a>
                    </li>
                {% empty %}
                    <li>暂无推荐</li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <!-- 翻页控件 -->
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?q={{ query }}&page=1">&laquo; first</a>
                <a href="?q={{ query }}&page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            
            {% if page_obj.has_next %}
                <a href="?q={{ query }}&page={{ page_obj.next_page_number }}">next</a>
                <a href="?q={{ query }}&page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</body>

</html>

myweb/templates/search.html
<!-- searchapp/templates/search.html -->
{% load static %}
{% load my_filters %}
<html>
<head>
    <title>博客搜索引擎Blog</title>
    <script src="{% static 'js/jquery.min.js' %}"></script> <!-- 确保已经加载了jQuery -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/result.css' %}">
</head>

<body>
    <div class="header">
        <!-- 搜索表单，让用户可以重新搜索 -->
        <div class="search-form">
            <form method="get" action="{% url 'search_results' %}">
                <input type="text" name="q" placeholder="Search..." value="{{ query }}">
                <select name="type">
                    <option value="standard" {% if query_type == "standard" %}selected{% endif %}>站内查询</option>
                    <option value="phrase" {% if query_type == "phrase" %}selected{% endif %}>短语查询</option>
                    <option value="wildcard" {% if query_type == "wildcard" %}selected{% endif %}>通配查询</option>
                </select>
                <!-- 新增排序方式选择 -->
                <select name="sort_method">
                    <option value="personalize_search" {% if sort_method == "personalize_search" %}selected{% endif %}>个性化查询</option>
                    <option value="pagerank_only" {% if sort_method == "pagerank_only" %}selected{% endif %}>仅PageRank</option>
                </select>
                <button type="submit">查询</button>
            </form>
        </div>
        <!-- 添加查看查询日志的链接 -->
        <a href="{% url 'view_search_logs' %}" class="search-log-link">查看查询日志</a>
    </div>
    <!-- 推荐文章区域 -->
    <div class="recommendations">
        <h2>也许你感兴趣～</h2>
        <ul>
            {% for url in recommendations %}
                <li class="recommend-Item">
                    <!-- 使用 url_to_title 字典来显示标题，如果字典中没有标题，则显示 URL -->
                    <a href="{{ url }}" onclick="recordClick('{{ url }}');" target="_blank">
                        {{ url_to_title|get_item:url|default:url }}
                    </a>
                </li>
            {% empty %}
                <li>暂无推荐</li>
            {% endfor %}
        </ul>
    </div>
</div>
</body>

</html>

myweb/templates/search_logs.html
<!-- searchapp/templates/search_logs.html -->
{% load static %}
<html>

<head>
    <title>查询日志</title>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/search_log.css' %}">
</head>

<body>
    <h1>查询日志</h1>
    <!-- 新增：显示最常搜索的关键词 -->
    <div class="section">
        <h2>最常搜索Top10</h2>
        <ul>
            {% for word, count in most_common_words %}
            <li>{{ word }}: {{ count }}</li>
            {% endfor %}
        </ul>
    </div>

    <!-- 现有的日志展示 -->
    <div class="section">
        <h2>查询日志展示</h2>
        <ul>
            {% for log in logs %}
            <li>
                <strong>用户:</strong> {{ log.user.username }}
                <strong>查询内容:</strong> {{ log.query }}
                <strong>时间:</strong> {{ log.timestamp }}
            </li>
            {% empty %}
            <li>没有查询日志记录。</li>
            {% endfor %}
        </ul>
    </div>

    <!-- 新增：显示最近点击的链接 -->
    <div class="section">
        <h2>最近点击链接</h2>
        <ul>
            {% for log in click_logs %}
            <li>
                <strong>用户:</strong> {{ log.user.username }}
                <strong>点击链接:</strong> <a href="{{ log.url }}" target="_blank">{{ log.url }}</a>
                <strong>点击时间:</strong> {{ log.timestamp }}
            </li>
            {% empty %}
            <li>没有点击链接记录。</li>
            {% endfor %}
        </ul>
    </div>

</body>

</html>